packages:
  common: !include packages/common.yaml
  nodemcu: !include packages/nodemcu.yaml
  uplift_desk: !include packages/uplift_desk.yaml

substitutions:
  device_id: uplift_desk
  device_name: Uplift Desk
  api_password: !secret uplift_desk_api_password
  ota_password: !secret uplift_desk_ota_password
  location: Study

  tx_pin: D6
  rx_pin: D5
